name: Tests
on:
  pull_request:
    branches:
      - "**"
    tags-ignore:
      - '*.*.*'
  push:
    branches:
      - "**"
    tags-ignore:
      - '*.*.*'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Bootstrap & install dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
      env:
        CI: true
    - name: Linting
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: lint
      env:
        CI: true
    - name: Unit tests
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: test
      env:
        CI: true